---

- hosts: srv
  become: yes
  become_method: sudo

  vars:
    bin_dir: "/root/bin" # without trailing slash
    bin_items:
      - lectl
      - leinfo
    source_path: "/scratch/le-utils/" # with trailing slash
    source_dest_root: "/usr/local/src"
    source_dest: "{{ source_dest_root }}/le-utils-current/" # with trailing slash
    source_link: "{{ source_dest_root }}/le-utils"
    source_lock: "{{ source_dest_root }}/le-utils-current.lock"
    source_lock_set: True

  tasks:
    - name: "Install packages FreeBSD"
      pkgng: name="{{ item }}"
      loop:
        - rsync
      when: ansible_os_family == "FreeBSD"
    - name: "Install packages Linux"
      package: name="{{ item }}"
      loop:
       - rsync
      when: ( ansible_os_family == "Debian" ) or
            ( ansible_os_family == "RedHat" )

      # Bug: Synchronize module asking for a password during playbook run #2156
      # https://github.com/ansible/ansible-modules-core/issues/2156
      # Fixed in ansible 2.0.1
      # Workaround: Make dest writeable by ansible_user and disable sudo

    - name: "Create {{ source_dest }}"
      file:
        path: "{{ source_dest }}"
        state: directory
#        owner: "{{ ansible_user }}"
#        group: "{{ (ansible_os_family == 'FreeBSD') | ternary('wheel', 'root') }}"
#        mode: "0775"
# NOTE: Setting owner,group,mode potentially makes synchronize not idempotent.

    - name: "Copy current source to {{ source_dest }}"
      synchronize:
        src: "{{ source_path }}"
        dest: "{{ source_dest }}"
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"
    
    - name: "Create symbolic link to {{ source_dest }}"
      file:
        src: "{{ source_dest }}"
        dest: "{{ source_link }}"
        state: link
        force: yes

# NOTE: file:touch is NOT idempotent. Use command.
#    - name: "Lock development version. Touch {{ source_lock }}"
#      file:
#        path: "{{ source_lock }}"
#        state: touch
#      when: source_lock_set
    
    - name: "Lock development version. Touch {{ source_lock }}"
      command: "touch {{ source_lock }}"
      args:
        creates: "{{ source_lock }}"
        warn: false
      when: source_lock_set
    
    - name: "Copy scripts to {{ bin_dir }}"
      copy:
        src: "{{ source_link }}/{{ item }}"
        dest: "{{ bin_dir }}/{{ item }}"
        remote_src: yes
        owner: "root"
        group: "{{ (ansible_os_family == 'FreeBSD') | ternary('wheel', 'root') }}"
        mode: "0755"
      loop: "{{ bin_items }}"
      when: not ansible_check_mode

    - name: "Use /usr/local/bin/bash in FreeBSD"
      lineinfile:
        path: "{{ bin_dir }}/{{ item }}"
        regexp: "^#!"
        line: "#!/usr/local/bin/bash"
      loop: "{{ bin_items }}"
      when:
        - ansible_os_family == "FreeBSD"
        - not ansible_check_mode

    - name: Use /bin/bash in Linux
      lineinfile:
        path: "{{ bin_dir }}/{{ item }}"
        regexp: "^#!"
        line: "#!/bin/bash"
      loop: "{{ bin_items }}"
      when:
        - ( ansible_os_family == "Debian" ) or
          ( ansible_os_family == "RedHat" )
        - not ansible_check_mode

# EOF
...
